name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies & restart server
        run: |
          git pull origin main
          sudo systemctl restart nginx