name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to /var/www/html and restart Nginx
        run: |
          cd actions-runner
          ./run.sh
          sudo rsync -av --delete $GITHUB_WORKSPACE/ /var/www/html/
          sudo systemctl restart nginx
